apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patchesStrategicMerge:
  - service-patch.yaml

images:
  - name: srshin80/my-sample-app
    newTag: latest
