apiVersion: v1
kind: Service
metadata:
  name: my-sample-app   # base/service.yaml 의 이름 (prefix는 자동 적용됨)
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32767   # 원하는 NodePort (안 쓰면 자동 배정됨)
